# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$rust\
$jobs\
$cmd_duration\
$time\
$line_break\
$character\
"""

[username]
style_root = 'bold red'
style_user = 'bold purple'
format = '[ zudydy]($style) in '
show_always = true

[directory]
style = 'bold blue'
format = '[ $path]($style)[$read_only]($read_only_style) '
truncation_length = 5
truncation_symbol = '…/'

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:red'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = '.'

[nodejs]
style = 'green'

[rust]
style = 'orange'

[package]

[jobs]
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 1_000
show_milliseconds = true
style = 'bold yellow'
show_notifications = true
min_time_to_notify = 30_000

[time]
disabled = false
time_format = "%T"
format = "at [$time]($style) "
style = "bold yellow"
